### ISSUE TITLE
相比MapReduce的不同之处

### ISSUE THREAD

**Issue by yvxiang** [baidu/shuttle#1]
那么shuttle相对于之前的MapReduce的特点是什么？我看到文档里说中间数据也是写磁盘的

**Comment by Kai-Zhang** [comment]
shuttle是基于Galaxy的，依靠Galaxy进行资源分配与调度，在架构上比传统的MapReduce简洁，同时为Galaxy增加流式计算的功能。
除此之外希望提供更加灵活的接口支持更多类型的流式计算模型。

**Comment by fxsjy** [comment]
@linyvxiang , 主要两点：
1） 两层调度，架构更清晰，资源维度的调度由galaxy负责， app维度的调度由shuttle负责；
2） 数据排序（shffule）的中间结果不落本地磁盘，目前暂时用hdfs，之后会基于一个分布式内存文件系统；

**Comment by linyvxiang** [comment]
也就是说调度方面有点像mesos
那么内存文件系统是类似Tachyon这种吗？

**Comment by Kai-Zhang** [comment]
内存文件系统目前只是一个初步的想法，因为使用分布式文件系统经过实验目前速度较好，因此内存文件系统并不是目前开发的重点。不过后期可能会增加这个来提高速度。
